name: Tyler Shadle
favicon: null
layout_spectrum: 0.18471648776903749
typography_spectrum: 0.34932880755513906
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.16596090514212847
  lightness: 0.5856178738176823
  saturation: 0.026913394453004003
  rhythmicContrast: 0.7297431237529963
purpose: []
